### ISSUE TITLE
Splitting nightly builds into separate branch?

### ISSUE THREAD

**Issue by charlesbluca** [conda-forge/rust-activation-feedstock#25]
### Comment:

I notice that this feedstock opts to do stable and nightly releases in a single branch by [parametrizing on `version`, `channel_sources`, and `channel_targets`](https://github.com/conda-forge/rust-activation-feedstock/blob/9401406e63e54ba4ca9f8e7d83b69ad66df57cd9/recipe/conda_build_config.yaml#L64-L72).

While this allows for the release of multiple versions in a single PR (e.g. https://github.com/conda-forge/rust-activation-feedstock/pull/24), it also means that someone needs to manually bump the stable version whenever a new `rust` version becomes available on conda-forge; this can be problematic for downstream packages that use `compiler('rust')` in their recipes that are dependent on the latest stable Rust.

Would it make sense to switch to the style of release being used for [rust-feedstock](https://github.com/conda-forge/rust-feedstock), where nightly releases are done on [a separate `dev` branch](https://github.com/conda-forge/rust-feedstock/tree/dev)? The thought process here is that we could then add a [`source` block](https://github.com/conda-forge/rust-feedstock/blob/8ba17bde0c5d861e447592582e27f157d6f11415/recipe/meta.yaml#L7-L19) to the stable recipe so that the update bot can automatically open PRs when a new Rust version is detected (e.g. https://github.com/conda-forge/rust-feedstock/pull/115); we'd also want something like `bot: {check_solvable: true}` to make sure that the upstream `rust` dependency is fulfilled.

Happy to help out with this if possible 🙂 

cc @jakirkham who I chatted about this with

**Comment by isuruf** [comment]
As the maintainer of this feedstock, I find the current way the easiest maintain both the main and dev versions. Unless you or @jakirkham commits to maintain the two branches and keep them in sync in a timely manner, this won't change.

**Comment by isuruf** [comment]
Given the lack of response, I guess you are unwilling to take on the maintenance burden. Closing.

**Comment by charlesbluca** [comment]
Hi @isuruf apologies for never getting back here 🙁 took some time to assess the need for `compiler('rust')` in the relevant projects I am working on and think we should be able to get by with `rust` for now, so the initial motivation for this refactor is resolved.

In the case that this does become relevant again, I am okay with taking on that maintenance burden and can look into the required work to do the refactor
