### ISSUE TITLE
Missing run-export on libgcc-ng on linux

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/rust-activation-feedstock#51]
As seen in https://github.com/conda-forge/staged-recipes/pull/26081, where it was necessary to add `{{ compiler("c") }}` just to get its [run-export](https://github.com/conda-forge/ctng-compiler-activation-feedstock/blob/bc40bf36410363e2f87cffdada4e33d302c9f7f6/recipe/meta.yaml#L36-L38) on `libgcc-ng`.

If rust-compiled binaries end up [needing](https://github.com/conda-forge/staged-recipes/pull/26081#discussion_r1572136159) `libgcc_s.so.1`, we should add the run-export here.

**Comment by isuruf** [comment]
We don't know what version of libgcc_s.so the rust compiler will use, so we don't know what the run_exports minimum version should be. Need some sort of transitive dependency run_exports.

**Comment by h-vetinari** [comment]
The SOVERIONS of the libraries in `libgcc-ng` haven't changed since at least [GCC 8](https://conda-metadata-app.streamlit.app/?q=conda-forge%2Flinux-64%2Flibgcc-ng-8.5.0-h9698f3f_19.tar.bz2), down to the patch level. They're not as sensitive to the runtime version as libstdcxx, so AFAICT we should be fine with `libgcc-ng >= 11.4`, i.e. the minimal GCC version we're still building.

It would IMO be an improvement over the current situation.
